### ISSUE TITLE
Trouble getting the new IP adaptor nodes + other error in workflow

### ISSUE THREAD

**Issue by jags111** [cozymantis/clothes-swap-salvton-comfyui-workflow#2]
Had trouble as IP adaptor node and model nodes got changed..in the new version. Please correct same in your workflow in the gum road also. secondly the Human Parser Pascal.. can you give an alternative to run same in the  current pipeline or else i need to do a face mask node and update it. As this is a paid version.. hope you can rectify and update all details on same.
![image](https://github.com/cozymantis/clothes-swap-salvton-comfyui-workflow/assets/5968619/86fc186e-605c-40cc-8fe1-f29e0bbb31da)
 Also the workflow needs to be updated in github for same with more examples on use cases.

**Comment by jags111** [comment]
after dropping the face swapper node i tried to run the workflow and it is giving error like this below
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\AI\comfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\comfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\comfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\cozy-sal-vton\SALVTONCustomNode.py", line 256, in run
    result_status = infer(
                    ^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\cozy-sal-vton\SALVTONCustomNode.py", line 33, in infer
    ourgen_model = load_checkpoint(
                   ^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\cozy-sal-vton\SALVTONCustomNode.py", line 20, in load_checkpoint
    params = torch.load(checkpoint_path, map_location=device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\comfyUI\venv\Lib\site-packages\torch\serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\comfyUI\venv\Lib\site-packages\torch\serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\comfyUI\venv\Lib\site-packages\torch\serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'models/sal-vton/pytorch_model.bin'

PLEASE note i have already git cloned the model from the source into the ComfyUI\models\sal-vton place

**Comment by gabidobo** [comment]
Hi @jags111!

- I've added support for the new IPAdapter v2
- I've added `workflow-no-head-detection.json` which skips detecting and rebuilding the entire head, which is what the Human Parser node did

Let me know if this works?

Also - the "No such file or directory" error seems to indicate the model file is missing from the expected location.
Your "comfyui/models/sal-vton" should look similar to:

<img width="395" alt="image" src="https://github.com/cozymantis/clothes-swap-salvton-comfyui-workflow/assets/5381731/f0b14201-f455-4254-a1c4-8851973c3cdb">

**Comment by jags111** [comment]
![image](https://github.com/cozymantis/clothes-swap-salvton-comfyui-workflow/assets/5968619/5298e4cb-d52c-44b8-a8f8-c7fe2850dc3f)
The directory is perfect and still not sure where the "models/sal-vton/pytorch_model.bin" is coming from.. Is it due to some mismatch of the  model.bin file. i downloaded three times and replaced it and still error. Can you post it somewhere so it will match perfect. This is caused due the dependencies failing the request.
![image](https://github.com/cozymantis/clothes-swap-salvton-comfyui-workflow/assets/5968619/610a58c1-b78e-425a-b85b-6ef4d3cb90d2)

**Comment by wandrzej** [comment]
Same exact issues., and the model file is in the right folder (note that with your exact instructions from gumroad, you'll end up with those in a subfolder, might be worth updating that as well)
Anyway, it might be a matter of either some linux specific paths, or similar issue, within the code. 

Regarding the human parser, I wasn't able to install it. 

```
`Traceback (most recent call last):
  File "d:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\__init__.py", line 1, in <module>
    from .HumanParserLIPCustomNode import HumanParserLIPCustomNode
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\HumanParserLIPCustomNode.py", line 5, in <module>
    from .utils import generate
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\utils.py", line 8, in <module>
    from .schp import networks
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\networks\__init__.py", line 3, in <module>
    from .AugmentCE2P import resnet101
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\networks\AugmentCE2P.py", line 21, in <module>
    from ..modules import InPlaceABNSync
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\bn.py", line 10, in <module>
    from .functions import *
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\functions.py", line 12, in <module>
    _backend = load(name="inplace_abn",
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "d:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "d:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1793, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "d:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1842, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

Cannot import D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node module for custom nodes: Ninja is required to load C++ extensions`
```

**Comment by wandrzej** [comment]
edit: 
OK, after a few tries I've managed to fix the paths, and that was exactly the problem. 

What's still bugging me that the quality is still waaay worst than the official demo. 
Left is the input image, second is the garment, 3rd is the official demo result and last is the output from your custom node. 
<img width="1323" alt="image" src="https://github.com/cozymantis/clothes-swap-salvton-comfyui-workflow/assets/26924000/0322cf05-eb08-4a73-991f-471d976cc330">

**Comment by gabidobo** [comment]
@wandrzej I'm happy to hear that fixing the paths solved the issue!

It looks like the landmarks are incorrectly detected in the result you posted. Have you tried editing/updating the landmarks, using the "update landmarks" button in the node?

One of the perks of SAL-VTON is that you can make the fit better by manually updating these landmarks, and I find it's often needed for best results.

**Comment by wandrzej** [comment]
regarding paths, it needs code change, so most people won't be able to fix it. You'd need ot update your code to handle the relative paths. if you are not running the portable windows version, you might not get those errors. 

I get that one can update the landmarks manually, but this is not required in the original code on exactly the same inputs. So there's something within the custom node, that makes it work differently.

**Comment by gabidobo** [comment]
@wandrzej interesting, can you please tell me where you needed to change the code? Are your files directly under `models/sal-vton`? Why do you think this is a Windows issue?

Re:landmarks - it is my understanding from the paper that the best results displayed have been obtained via manual manipulation of the detected landmarks, that's sort of the "perk" of this method. But I'm definitely open to re-investigating the implementation to find any issues.

Also, could you please let me know where you found the leather jacket example above? As it's not part of the original paper - https://openaccess.thecvf.com/content/CVPR2023/papers/Yan_Linking_Garment_With_Person_via_Semantically_Associated_Landmarks_for_Virtual_CVPR_2023_paper.pdf. I think upper-body, white background images are recommended for best results.

**Comment by gabidobo** [comment]
Closing this for now since it's been inactive.
